publish_mode: editorial_workflow
backend:
  name: github
  repo: chrismade/blog002
  base_url: https://rqawxtha1j.execute-api.eu-west-1.amazonaws.com
  auth_endpoint: /prod/auth
site_id: blog.acmattheis.de
media_folder: "static/images" 
public_folder: "/images" 
collections:
  - name: "basics" # Used in routes, e.g., /admin/collections/blog
    label: "Website" # Used in the UI
    folder: "content/basics"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured image", name: "thumbnail", widget: "image"}
      - {label: "Categories", name: "categories", widget: "list", default: ["news"]}
      - {label: "Body", name: "body", widget: "markdown"}
